In [1]:
import os
import dgl
import ot
import torch

os.environ['DGLBACKEND'] = "pytorch" 
import dgl.function as fn
import torch.nn as nn
import scanpy as sc

import graph

In [2]:
import graph

ANNDATA_DIR = 'annData'
DLPFC_ANNDATA_DIR = os.path.join(ANNDATA_DIR, '1.DLPFC')

In [3]:
test_sample_id = '151507'
sample = sc.read_h5ad(os.path.join(DLPFC_ANNDATA_DIR, "{}.h5ad".format(test_sample_id)))
sample

/home/edgar/miniconda3/envs/STGCNDBC/lib/python3.11/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


AnnData object with n_obs × n_vars = 4226 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'layer_guess'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'layer_guess_colors', 'spatial'
    obsm: 'spatial'

In [4]:
# Create a DGL graph object
g = graph.create_dgl_graph(sample)

In [5]:
g.nodes()

tensor([   0,    1,    2,  ..., 4223, 4224, 4225])

In [6]:
g.edges()

(tensor([   0,    0,    0,  ..., 4224, 4225, 4225]),
 tensor([   1,    2,    3,  ..., 4223, 4223, 4224]))

In [7]:
g.edges(form='all')

(tensor([   0,    0,    0,  ..., 4224, 4225, 4225]),
 tensor([   1,    2,    3,  ..., 4223, 4223, 4224]),
 tensor([       0,        1,        2,  ..., 17854847, 17854848, 17854849]))

In [8]:
sg = graph.create_random_dgl_subgraph(g, 20)

In [9]:
def test_udf(edges):
    print(edges.src)
    print(edges.dst)
    print(edges.data)
    

In [11]:
g.ndata['x']

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [12]:
similarity = ot.dist(g.ndata['x'])
similarity


tensor([[    0., 52125., 16961.,  ...,  1945., 22664., 22920.],
        [52125.,     0., 19884.,  ..., 54062., 14395., 18941.],
        [16961., 19884.,     0.,  ..., 18792.,  7577.,  5501.],
        ...,
        [ 1945., 54062., 18792.,  ...,     0., 24089., 23897.],
        [22664., 14395.,  7577.,  ..., 24089.,     0.,  8482.],
        [22920., 18941.,  5501.,  ..., 23897.,  8482.,     0.]])

In [ ]:
similarity[7,8]

tensor(41722.)

In [ ]:
similarity[g.edges()]

tensor([52125., 16961., 18550.,  ..., 24089., 23897.,  8482.])

In [ ]:
len(g.edges()[0])

17854850

In [ ]:
# sim = [similarity[u][v] for u,v in g.edges()]

In [ ]:
sg.apply_edges(test_udf)